replicaCount: 1

image:
  repository: isaza612/trabajo-final
  tag: "4.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

ingress:
  enabled: true
  className: "nginx"
  host: trabajo.local
  path: /api
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
