apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: {{ .Values.postgresql.host }}.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "{{ .Values.postgresql.port }}"
  DB_NAME: {{ .Values.postgresql.auth.database }}
