apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: trabajo-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: pedido
            - name: POSTGRES_PASSWORD
              value: pedido123
            - name: POSTGRES_DB
              value: pedido_db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
